version: '3.9'

services:
  api:
    container_name: products_categories
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_USER=pedro
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB=products_management
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=pedro
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB= products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedro -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

